"""Lift every `ast.Lambda` to a named `def` — a late, behaviour-preserving normalization so the
obfuscated output contains no anonymous `lambda` tells (user lambdas AND ones generated by later
stages: the attest decoy/oracle closures, the anti-trace blackholes).

Each lambda becomes `def <fresh>(<args>): return <body>` inserted immediately before the statement
that used it (same scope), and the lambda is replaced by a Name load of <fresh>. Closures are
preserved: the def lives in the lambda's scope and Python closures are late-binding, exactly like a
lambda. Nested lambdas fall out of the fixpoint — once the outer lambda is a def, the inner one's
enclosing statement is that def's `return`, so it is lifted INTO the def (capturing the def's params).

Runs LATE (before finalize_names) so the fresh `_pyobf_g<n>` names are finalized to `_pyobf_<hex>`
and recorded in the sourcemap (role "lam"). Lambdas inside a comprehension/generator scope are left
as-is — lifting them out would change which scope their free variables resolve in.
"""
from __future__ import annotations

import ast

from .names import Namer, collect_names

_COMP = (ast.ListComp, ast.SetComp, ast.DictComp, ast.GeneratorExp)
_SCOPE = (ast.FunctionDef, ast.AsyncFunctionDef, ast.Module, ast.ClassDef)


def lift_lambdas(tree: ast.AST, namer: Namer | None = None) -> ast.AST:
    """Replace every liftable lambda in `tree` with a named def, in place. Idempotent."""
    if namer is None:
        namer = Namer(taken=collect_names(tree))
    guard = 0
    while _lift_one(tree, namer):
        guard += 1
        if guard > 1_000_000:  # one lambda removed per pass; backstop against impossible loops
            raise RuntimeError("lift_lambdas: runaway")
    ast.fix_missing_locations(tree)
    return tree


def _parent_map(tree):
    """id(child) -> (parent, field, index|None) for every AST child (list elements get their index)."""
    out = {}
    for parent in ast.walk(tree):
        for field, value in ast.iter_fields(parent):
            if isinstance(value, list):
                for idx, item in enumerate(value):
                    if isinstance(item, ast.AST):
                        out[id(item)] = (parent, field, idx)
            elif isinstance(value, ast.AST):
                out[id(value)] = (parent, field, None)
    return out


def _lift_one(tree, namer) -> bool:
    parents = _parent_map(tree)
    for node in ast.walk(tree):
        if isinstance(node, ast.Lambda) and not _in_comprehension(node, parents):
            return _do_lift(node, namer, parents)
    return False


def _in_comprehension(node, parents) -> bool:
    """True if a comprehension/generator encloses `node` before its nearest def/class/module scope."""
    cur = node
    while id(cur) in parents:
        p, _, _ = parents[id(cur)]
        if isinstance(p, _COMP):
            return True
        if isinstance(p, _SCOPE):
            return False
        cur = p
    return False


def _enclosing_stmt(node, parents):
    """The nearest ancestor statement that is a direct element of a statement list.
    Returns (list, index, stmt) or (None, None, None)."""
    cur = node
    while id(cur) in parents:
        p, field, idx = parents[id(cur)]
        if isinstance(cur, ast.stmt) and idx is not None and isinstance(getattr(p, field), list):
            return getattr(p, field), idx, cur
        cur = p
    return None, None, None


def _do_lift(lam, namer, parents) -> bool:
    stmt_list, idx, _stmt = _enclosing_stmt(lam, parents)
    if stmt_list is None:
        return False  # no statement context to place the def — leave the lambda (should not happen)
    name = namer.fresh("lam", kind="func")
    fn = ast.FunctionDef(name=name, args=lam.args, body=[ast.Return(value=lam.body)],
                         decorator_list=[], returns=None)
    fn.type_params = []          # required field on 3.12+
    ast.copy_location(fn, lam)
    # replace the lambda with a load of the new name in its parent
    p, field, fidx = parents[id(lam)]
    repl = ast.copy_location(ast.Name(id=name, ctx=ast.Load()), lam)
    if fidx is None:
        setattr(p, field, repl)
    else:
        getattr(p, field)[fidx] = repl
    stmt_list.insert(idx, fn)    # def executes before the statement that now refers to it
    # Rename the lifted def's own params/locals to fresh obfuscator names (the lambda's param names
    # would otherwise survive as plaintext). Scope-aware so captured free vars (bound in an enclosing
    # scope) are left intact; names are minted from the global counter and unified by finalize.
    from .passes.localrename import rename_simple_helper_locals
    rename_simple_helper_locals(ast.Module(body=[fn], type_ignores=[]), namer)
    return True
